DAC6-1779: Add option to print/save page to FileErrorView
hmrc/mandatory-disclosure-rules-frontend pull request #151
Opened 2023-02-03 09:12 UTC by HarryHamilton

2023-02-03 12:01 UTC, BriWak requested changes

2023-02-03 12:01 UTC, BriWak commented on project/AppDependencies.scala
> +  val mongoplay_ver = "0.73.0"
One small comment. Other than that this looks good to me.

Can you just make this camelCase for consistency. just something like
`val mongoVersion = "0.73.0"`

2023-02-03 12:03 UTC, BriWak submitted a review, later dismissed

2023-02-07 11:05 UTC, mahipal-padala approved these changes

2023-02-07 11:05 UTC, merged